on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Test Suite

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

        include:
          # Test MSRV
          - rust: 1.49.0

          # Test nightly but don't fail
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
